export enum EnvKey {
  JWT_SECRET_KEY_BASE64 = 'JWT_SECRET_KEY_BASE64',
  JWT_PUBLIC_KEY_BASE64 = 'JWT_PUBLIC_KEY_BASE64',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
  JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN',
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',
  PORT = "PORT"
}

export type EnvKeys = {
  [EnvKey.JWT_SECRET_KEY_BASE64]: string,
  [EnvKey.JWT_PUBLIC_KEY_BASE64]: string,
  [EnvKey.JWT_REFRESH_EXPIRES_IN]: number,
  [EnvKey.JWT_ACCESS_EXPIRES_IN]: number,
  [EnvKey.NODE_ENV]: string
  [EnvKey.DATABASE_URL]: string
  [EnvKey.PORT]: number
}